# -*- coding: utf-8 -*-
"""Git testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8RqsJZrCCWAdXObCUTV30pwz7hr0LGN
"""

import pandas as pd
import numpy as np
import gradio as gr
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

df=pd.read_csv("Housing.csv")

#seperate features and target
x=df.drop("price",axis=1)
y = df["price"]

#feature engineering
x["total_rooms"] = x["bedrooms"] + x["bathrooms"]
x["area_per_room"] = x["area"] / (x["bedrooms"] + 1)

#finding the column types
num_cols = ["area", "bedrooms", "bathrooms", "stories", "parking",
            "total_rooms", "area_per_room"]

cat_cols = ["mainroad", "guestroom", "basement",
            "hotwaterheating", "airconditioning",
            "prefarea", "furnishingstatus"]

num_pipeline = Pipeline([
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([
  OneHotEncoder(drop="first", handle_unknown="ignore")
 ])

num_pipeline = Pipeline([
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([
    ("encoder", OneHotEncoder(drop="first", handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

#pipeline process
model_pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=200,
        random_state=42
    ))
])

#training and testing
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

model_pipeline.fit(x_train, y_train)



def predict_price(area, bedrooms, bathrooms, stories, parking,
                  mainroad, guestroom, basement,
                  hotwaterheating, airconditioning,
                  prefarea, furnishingstatus):

    total_rooms = bedrooms + bathrooms
    area_per_room = area / (bedrooms + 1)

    input_df = pd.DataFrame([[area, bedrooms, bathrooms, stories, parking,
                              total_rooms, area_per_room,
                              mainroad, guestroom, basement,
                              hotwaterheating, airconditioning,
                              prefarea, furnishingstatus]],
                            columns=num_cols + cat_cols)

    prediction = model_pipeline.predict(input_df)[0]

    return f" Predicted House Price: ₹ {prediction:,.0f}"

interface = gr.Interface(
    fn=predict_price,
    inputs=[
        gr.Number(label="Area (sq ft)", value=3000),
        gr.Number(label="Bedrooms", value=3),
        gr.Number(label="Bathrooms", value=2),
        gr.Number(label="Stories", value=2),
        gr.Number(label="Parking Spaces", value=1),

        gr.Radio(["yes", "no"], label="Main Road"),
        gr.Radio(["yes", "no"], label="Guest Room"),
        gr.Radio(["yes", "no"], label="Basement"),
        gr.Radio(["yes", "no"], label="Hot Water Heating"),
        gr.Radio(["yes", "no"], label="Air Conditioning"),
        gr.Radio(["yes", "no"], label="Preferred Area"),
        gr.Dropdown(["furnished", "semi-furnished", "unfurnished"],
                    label="Furnishing Status")
    ],
    outputs="text",
    title=" House Price Prediction System",
    description="Enter house details to predict its market price using Machine Learning."
)

interface.launch()

