# -*- coding: utf-8 -*-
"""Git testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8RqsJZrCCWAdXObCUTV30pwz7hr0LGN
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

#reading the data
df=pd.read_csv('Housing.csv')

#doing some basic operations
df.head()
df.info()
df.describe()

#choosing the features what we need
x = df.drop("price", axis=1)
y = df["price"]

#converting the categorical to numberical data
num_cols = ["area", "bedrooms", "bathrooms", "stories", "parking"]

cat_cols = ["mainroad", "guestroom", "basement",
            "hotwaterheating", "airconditioning",
            "prefarea", "furnishingstatus"]

x = pd.get_dummies(x, columns=cat_cols, drop_first=True)

print(X.shape)
X.head()

#splitting the Data for an training and testing
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#Training a model

from sklearn.linear_model import LinearRegression

model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

#checking the performance of the metrics
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("RMSE:", rmse)
print("R2  :", r2)

