# -*- coding: utf-8 -*-
"""Git testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8RqsJZrCCWAdXObCUTV30pwz7hr0LGN
"""

#importing the libraries
import pandas as pd
import numpy as np
from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_percentage_error
from catboost.utils import eval_metric
import warnings
warnings.filterwarnings("ignore")

#loading the dataset
df = pd.read_csv("Sales-Export_2019-2020.csv")

#Column cleaning
df.columns = df.columns.str.strip()

#convert Date Columns
df["date"] = pd.to_datetime(df["date"])

# Remove commas from numeric columns

df["order_value_EUR"] = (
    df["order_value_EUR"]
    .astype(str)
    .str.replace(",", "")
    .astype(float)
)

df["cost"] = (
    df["cost"]
    .astype(str)
    .str.replace(",", "")
    .astype(float)
)

# Aggregate DAILY sales

daily_sales = (
    df.groupby("date", as_index=False)
      .agg({"order_value_EUR": "sum"})
)

daily_sales.rename(columns={"order_value_EUR": "sales"}, inplace=True)

#Time Feature Engineering
def create_time_features(data):
    data = data.copy()

    data["year"] = data["date"].dt.year
    data["month"] = data["date"].dt.month
    data["day"] = data["date"].dt.day
    data["weekday"] = data["date"].dt.weekday
    data["dayofyear"] = data["date"].dt.dayofyear
    data["weekofyear"] = data["date"].dt.isocalendar().week.astype(int)
    data["quarter"] = data["date"].dt.quarter
    data["is_weekend"] = data["weekday"].isin([5, 6]).astype(int)

    # Cyclical encoding
    data["month_sin"] = np.sin(2 * np.pi * data["month"] / 12)
    data["month_cos"] = np.cos(2 * np.pi * data["month"] / 12)
    data["day_sin"] = np.sin(2 * np.pi * data["weekday"] / 7)
    data["day_cos"] = np.cos(2 * np.pi * data["weekday"] / 7)

    return data

daily_sales = create_time_features(daily_sales)

#Train test Split
train = daily_sales[daily_sales["date"] < "2020-01-01"]
test = daily_sales[daily_sales["date"] >= "2020-01-01"]

X_train = train.drop(columns=["date", "sales"])
y_train = train["sales"]

X_test = test.drop(columns=["date", "sales"])
y_test = test["sales"]

# Model Training
model = CatBoostRegressor(
    iterations=500,
    learning_rate=0.1,
    depth=8,
    random_state=42,
    verbose=False
)
model.fit(X_train, y_train)

# Prediction
predictions = model.predict(X_test)

# Evaluation
smape = eval_metric(y_test.values, predictions, "SMAPE")[0]
mape = mean_absolute_percentage_error(y_test, predictions)

print("=== Model Performance ===")
print(f"SMAPE : {smape:.4f}")
print(f"MAPE  : {mape:.4f}")

# Feature Importance
print("\n=== Feature Importance ===")
importance = model.get_feature_importance()

for feature, score in zip(X_train.columns, importance):
    print(f"{feature:15s} : {score:.4f}")

