# -*- coding: utf-8 -*-
"""Ml Students Score System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mEqN8wjyt6lA7pN1G80k1LftgSLGOpwT
"""

import pandas as pd

df=pd.read_csv('students.csv')

df.sort_values(by='Marks',ascending=False)

import matplotlib.pyplot as plt

plt.scatter(df['Hours_Studied'],df['Marks'])
plt.title("Hours vs Marks")
plt.xlabel("Hours_Studied")
plt.ylabel("Marks")
plt.ylabel("Marks scored")
plt.show()

from sklearn.model_selection import train_test_split

x=df[['Hours_Studied']]

y=df['Marks']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

x_test

from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(x_train,y_train)

model.predict(x_test)







