# -*- coding: utf-8 -*-
"""Olympics Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8RqsJZrCCWAdXObCUTV30pwz7hr0LGN
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

#Loading the Data
df = pd.read_csv("dataset_olympics.csv")
df.head()

#choosing the correct columns and the feature selection
ml_df = df[["Sex","Age","Height","Weight","Sport","NOC","Medal"]]
ml_df.head()

#checking is there any missing
ml_df.isnull().sum()
ml_df = ml_df.dropna()

#the ml model will only understand the 0 and 1 so now we are converted the text it into categorical value
le = LabelEncoder()

ml_df["Sex"] = le.fit_transform(ml_df["Sex"])
ml_df["Sport"] = le.fit_transform(ml_df["Sport"])
ml_df["NOC"] = le.fit_transform(ml_df["NOC"])
ml_df["Medal"] = le.fit_transform(ml_df["Medal"])

ml_df.head()

#seperating the data with an test and training
X = ml_df.drop("Medal", axis=1)
y = ml_df["Medal"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#using the model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

#confusion matrix
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

sample = X_test.iloc[0].values.reshape(1, -1)

pred = model.predict(sample)

pred_label = le.inverse_transform(pred)

actual_label = le.inverse_transform([y_test.iloc[0]])

print("Predicted Medal :", pred_label[0])
print("Actual Medal    :", actual_label[0])

