# -*- coding: utf-8 -*-
"""sales forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKh3S7wr22HKN4sOOLKMRU_wf_jI_tMT
"""

import pandas as pd
import numpy as np
from catboost import CatBoostRegressor
from catboost.utils import eval_metric
from sklearn.metrics import mean_absolute_percentage_error
import warnings
warnings.filterwarnings('ignore')

def create_time_features(df):
    df_copy = df.copy()
    df_copy['year'] = df_copy['date'].dt.year
    df_copy['month'] = df_copy['date'].dt.month
    df_copy['quarter'] = df_copy['date'].dt.quarter
    df_copy['dayofweek'] = df_copy['date'].dt.dayofweek
    df_copy['dayofyear'] = df_copy['date'].dt.dayofyear
    df_copy['weekofyear'] = df_copy['date'].dt.isocalendar().week
    df_copy['is_weekend'] = (df_copy['date'].dt.dayofweek >= 5).astype(int)

    # Cyclical features for month and dayofweek
    df_copy['month_sin'] = np.sin(2 * np.pi * df_copy['month']/12)
    df_copy['month_cos'] = np.cos(2 * np.pi * df_copy['month']/12)
    df_copy['day_sin'] = np.sin(2 * np.pi * df_copy['dayofweek']/7)
    df_copy['day_cos'] = np.cos(2 * np.pi * df_copy['dayofweek']/7)

    return df_copy

df_enriched = create_time_features(df)

train = df_enriched[df_enriched["date"] < "2017-01-01"]
test = df_enriched[df_enriched["date"] >= "2017-01-01"]

train_features_original = train[['store', 'item']].copy()
train_features_original['date'] = train['date']
test_features_original = test[['store', 'item']].copy()
test_features_original['date'] = test['date']

train_target = train["sales"]
test_target = test["sales"]

feature_columns = ['store', 'item', 'year', 'month', 'quarter', 'dayofweek',
                   'dayofyear', 'weekofyear', 'is_weekend', 'month_sin',
                   'month_cos', 'day_sin', 'day_cos']

train_features_enriched = train[feature_columns].copy()
test_features_enriched = test[feature_columns].copy()

model = CatBoostRegressor(verbose=False, allow_writing_files=False, random_state=0)
print("=== Original Features (without enrichment) ===")

model.fit(train_features_original[['store', 'item']], train_target)
preds_original = model.predict(test_features_original[['store', 'item']])
smape_original = eval_metric(test_target.values, preds_original, "SMAPE")
mape_original = mean_absolute_percentage_error(test_target, preds_original)

print(f"SMAPE with original features: {smape_original[0]:.4f}")
print(f"MAPE with original features: {mape_original:.4f}")

print("\n=== Enriched Features (with time-based features) ===")

model.fit(train_features_enriched, train_target)
preds_enriched = model.predict(test_features_enriched)
smape_enriched = eval_metric(test_target.values, preds_enriched, "SMAPE")
mape_enriched = mean_absolute_percentage_error(test_target, preds_enriched)

print(f"SMAPE with enriched features: {smape_enriched[0]:.4f}")
print(f"MAPE with enriched features: {mape_enriched:.4f}")

improvement = ((smape_original[0] - smape_enriched[0]) / smape_original[0]) * 100
print(f"\nImprovement with feature engineering: {improvement:.2f}%")

print("\n=== Feature Importance ===")
feature_importance = model.get_feature_importance()
for feature, importance in zip(feature_columns, feature_importance):
    print(f"{feature}: {importance:.4f}")

results_df = pd.DataFrame({
    'Model': ['Original Features', 'Enriched Features'],
    'SMAPE': [smape_original[0], smape_enriched[0]],
    'MAPE': [mape_original, mape_enriched]
})

print("\n=== Results Summary ===")
print(results_df)